### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by coremaya** [kycd/bookwalker-fetch-final-publish#1]

**Comment by kycd** [comment]
hi

this tool could only fetch the ** publish date ** of the last volume of a series book on https://www.bookwalker.com.tw/

You may try to access this endpoint to get the sample result of this tool https://asia-northeast1-acoustic-art-251908.cloudfunctions.net/BwWishlist

To custom the series to fetch, you need send POST request, you may find the detail HTTP command at README of this repository.

This repository base on gcp cloud function, it's need to deploy to get an http trigger, you may find the detail command at README of this repository.

Best regard.
